import { useEffect, useState } from "react";
import { Alert, Button, Input, Label, Table } from "reactstrap";
import PageShell from "@/components/salon/PageShell";
import { useAuth } from "@/auth/AuthContext";
import { salonApi } from "@/services/salonApi";
import { formatDate, formatMoney, labelize } from "@/utils/salonFormat";
import ReportExportButtons from "@/components/salon/ReportExportButtons";
import RowActionsMenu from "@/components/salon/RowActionsMenu";

const now=new Date();
const SalarySlips=()=>{const{user}=useAuth();const manager=["SUPER_ADMIN","SALON_ADMIN","BRANCH_MANAGER"].includes(user?.role);const[rows,setRows]=useState([]),[staff,setStaff]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState("");const[form,setForm]=useState({staffId:"",month:now.getMonth()+1,year:now.getFullYear(),bonusAmount:0,manualDeduction:0,note:""});
const load=async()=>{try{const[a,b]=await Promise.all([salonApi.salarySlips.list({month:form.month,year:form.year}),manager?salonApi.staff.list():Promise.resolve({data:[]})]);setRows(a.data||[]);setStaff(b.data||[]);}catch(e){setError(e.message);}};useEffect(()=>{load();},[form.month,form.year,manager]);
const action=async(fn)=>{try{setError("");await fn();await load();}catch(e){setError(e.message);}};const pdf=async(x)=>{try{const blob=await salonApi.salarySlips.pdf(x.id);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`salary-slip-${x.staff?.staffCode||x.staffId}-${x.month}-${x.year}.pdf`;a.click();URL.revokeObjectURL(url);}catch(e){setError(e.message);}};
return <PageShell title="Salary Slips" description="Generate immutable payroll snapshots, pay, cancel, and download PDFs." tools={<ReportExportButtons reportType="payroll" filters={{month:form.month,year:form.year}} />}>{error&&<Alert color="danger">{error}</Alert>}{manager&&<div className="card card-bordered mb-4"><div className="card-inner d-flex flex-wrap gap-3 align-items-end"><div><Label>Staff</Label><Input type="select" value={form.staffId} onChange={e=>setForm({...form,staffId:e.target.value})}><option value="">Select</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Input></div><div><Label>Month</Label><Input type="number" min="1" max="12" value={form.month} onChange={e=>setForm({...form,month:e.target.value})}/></div><div><Label>Year</Label><Input type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></div><div><Label>Bonus</Label><Input type="number" value={form.bonusAmount} onChange={e=>setForm({...form,bonusAmount:e.target.value})}/></div><div><Label>Deduction</Label><Input type="number" value={form.manualDeduction} onChange={e=>setForm({...form,manualDeduction:e.target.value})}/></div><Button color="primary" onClick={()=>action(()=>salonApi.salarySlips.generate({...form,month:Number(form.month),year:Number(form.year),bonusAmount:Number(form.bonusAmount),manualDeduction:Number(form.manualDeduction)}))}>Generate</Button></div></div>}
{selected&&<div className="card card-bordered mb-4"><div className="card-inner"><div className="d-flex justify-content-between"><h5>{selected.staff?.name} — {selected.month}/{selected.year}</h5><Button size="sm" close onClick={()=>setSelected(null)}/></div><div className="row g-2"><div className="col-md-4">Attendance: {selected.presentDays} present, {selected.halfDays} half, {selected.lateDays} late</div><div className="col-md-4">Leaves: {selected.paidLeaveDays} paid, {selected.unpaidLeaveDays} unpaid</div><div className="col-md-4">Late penalty: {formatMoney(selected.latePenalty)}</div><div className="col-md-4">Service commission: {formatMoney(selected.serviceCommissionAmount)}</div><div className="col-md-4">Retail commission: {formatMoney(selected.retailCommissionAmount)}</div><div className="col-md-4"><strong>Net: {formatMoney(selected.netSalary)}</strong></div></div></div></div>}
<div className="card card-bordered"><Table responsive className="mb-0"><thead><tr><th>Staff</th><th>Period</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Status</th><th className="text-end">Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.staff?.name}</td><td>{x.month}/{x.year}</td><td>{formatMoney(x.grossSalary)}</td><td>{formatMoney(Number(x.unpaidLeaveDeduction)+Number(x.latePenalty)+Number(x.manualDeduction))}</td><td>{formatMoney(x.netSalary)}</td><td>{labelize(x.status)}{x.paidAt&&<small className="d-block">{formatDate(x.paidAt)}</small>}</td><td className="text-end"><RowActionsMenu><Button size="sm" outline onClick={()=>action(async()=>setSelected((await salonApi.salarySlips.get(x.id)).data))}>View</Button><Button size="sm" outline onClick={()=>pdf(x)}>PDF</Button>{manager&&x.status==="GENERATED"&&<><Button size="sm" color="success" onClick={()=>action(()=>salonApi.salarySlips.markPaid(x.id))}>Mark paid</Button><Button size="sm" color="danger" outline onClick={()=>action(()=>salonApi.salarySlips.cancel(x.id))}>Cancel</Button></>}</RowActionsMenu></td></tr>)}</tbody></Table></div></PageShell>};
export default SalarySlips;
